work_dir: ./work_dir/uav2/bonet

# feeder
feeder: feeders.feeder_uav.Feeder
train_feeder_args:
  data_path: data/uav2/bone.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 250
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: data/uav2/bone.npz
  split: test
  window_size: 250
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.ctrgcnt.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.graph.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [30, 50]
warm_up_epoch: 5

# training
device: [0,1]
batch_size: 64
test_batch_size: 256
num_epoch: 60
nesterov: True
